### ISSUE TITLE
Adding Custom I18n setting

### ISSUE THREAD

**Issue by mcentrih** [FlowingCode/ErrorWindowAddon#43]
It would be very good if you would allow to set custom I18n text for whole dialog globaly. So that we would not need to set text in every error case each.

![image](https://user-images.githubusercontent.com/79508499/192270515-7792f02e-b7ab-4048-9fd6-28878200fdf9.png)

**Comment by javier-godoy** [comment]
Hello. If you don't need to support multiple languages, you can set up a custom i18n instance globally by replacing the default ErrorWindowFactory. In order to do so, set up a [VaadinServiceInitListener](https://vaadin.com/docs/latest/advanced/service-init-listener) as follows:


```
@Component
public class ErrorWindowServiceInitListener
        implements VaadinServiceInitListener {

  @Override
  public void serviceInit(ServiceInitEvent event) {
    ErrorWindowI18n i18n = new ErrorWindowI18n();
    i18n.setCaption(...);
    i18n.setCaption(...);
 
    ErrorManager.setErrorWindowFactory(Throwable.class, details -> new ErrorWindow(details).open());        
  }
}
``` 

Please let us know if that helped.

**Comment by javier-godoy** [comment]
While my comment above allows customizing the texts globally, it does not allow to **resolve them based on the locale of the current UI**, which is a desirable feature.
